#!/bin/bash
echo "=== 检查今日请求数据 ==="
echo ""
echo "1. 检查usage_logs表中的最新记录："
docker exec codex-gateway-db-1 psql -U postgres -d codex_gateway -c "SELECT created_at, model, total_tokens FROM usage_logs ORDER BY created_at DESC LIMIT 5;"
echo ""
echo "2. 检查今天的记录数（使用CURRENT_DATE）："
docker exec codex-gateway-db-1 psql -U postgres -d codex_gateway -c "SELECT COUNT(*) as today_count FROM usage_logs WHERE created_at >= CURRENT_DATE AND created_at < CURRENT_DATE + INTERVAL '1 day';"
echo ""
echo "3. 检查数据库时区设置："
docker exec codex-gateway-db-1 psql -U postgres -d codex_gateway -c "SHOW timezone;"
echo ""
echo "4. 检查当前数据库时间："
docker exec codex-gateway-db-1 psql -U postgres -d codex_gateway -c "SELECT NOW(), CURRENT_DATE, CURRENT_TIMESTAMP;"
echo ""
echo "5. 检查最近24小时的记录数："
docker exec codex-gateway-db-1 psql -U postgres -d codex_gateway -c "SELECT COUNT(*) as last_24h_count FROM usage_logs WHERE created_at >= NOW() - INTERVAL '24 hours';"
echo ""
echo "6. 检查所有记录的日期分布："
docker exec codex-gateway-db-1 psql -U postgres -d codex_gateway -c "SELECT DATE(created_at) as date, COUNT(*) as count FROM usage_logs GROUP BY DATE(created_at) ORDER BY date DESC LIMIT 10;"
